CC = gcc
CFLAGS = -g -Wall -std=c99 -I/usr/include/tirpc
LDLIBS = -ltirpc

all: motd_client motd_server

motd_client: motd_clnt.c motd_client.c motd.h
	$(CC) $(CFLAGS) -o motd_client motd_clnt.c motd_client.c $(LDLIBS)

motd_server: motd_svc.c motd_server.c motd.h
	$(CC) $(CFLAGS) -o motd_server motd_svc.c motd_server.c $(LDLIBS)
